# Generated by Django 3.1.2 on 2020-11-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_category_catimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catimg',
            field=models.ImageField(blank=True, null=True, upload_to='cat_img'),
        ),
    ]
